### PR TITLE
Calculator App Milestone 5

### PR DESCRIPTION
**Pull request by jaspreet-singh-sahota**
## In this milestone I did the following:

- Converted App function to a stateful component (Class).
- Implemented a handleClick function which takes btnName as an argument and changes the state based on the result of the calculate function. 
- In ButtonPanel component I implemented the handleClick function which takes btnName as an argument and returns clickHandler from props.
- Passed the clickHandler property to each button in the panel.
- Used event listeners to attach the handleClick event to every button.

[Heroku Live Link](https://jassi-calculator-app.herokuapp.com/)

Looking forward to your feedback 

Jaspreet Singh

### CODE REVIEW

**Review by whiz25 — APPROVED** [review]
## Approved :clap:
All checks are green for this milestone. Merge and proceed to the next project.

### Martin Afani

**Comment by jaspreet-singh-sahota** [comment]
Martin Afani,
 
Thank you for the green flag and for reviewing my code.

Best regards,

Jaspreet Singh

**Comment by jaspreet-singh-sahota** [comment]
My question for the TSE,

My 5th milestone got approved and I have to make some changes in the 4th one. So, do I need to go back to the 4th milestone and repeat the same code again? or I am good to go. 

Note:-  This is my 5th milestone pull request which I am sending for review instead of 4th.

Looking forward to your answer,
Best regards,
Jaspreet Singh

**Comment by Oghenebrume50** [comment]
Hi isn't this approved already? what changes are you talking about

cc: @whiz25

**Comment by jaspreet-singh-sahota** [comment]
# My question for the TSE,

My 5th milestone got approved and I have to make some changes in the 4th one which I have already completed in the 5th milestone. So, do I need to go back to the 4th milestone and repeat the same code again? or am I good to go?.

## Note:- This is my 5th milestone pull request which I am sending for review instead of 4th.

Looking forward to your answer,
Best regards,
Jaspreet Singh

**Comment by Forison** [comment]
> # My question for the TSE,
> My 5th milestone got approved and I have to make some changes in the 4th one which I have already completed in the 5th milestone. So, do I need to go back to the 4th milestone and repeat the same code again? or am I good to go?.
> 
> ## Note:- This is my 5th milestone pull request which I am sending for review instead of 4th.
> Looking forward to your answer,
> Best regards,
> Jaspreet Singh

First of all, it is not a good practice to work on different milestones simultaneously. You have to work according to the order milestone as each milestone has its own specific learning objective. Now you need to work on the review of the 4th milestone. The person who reviewed the 5th milestone only focused on the requirements of the 5th milestone in the review of that particular milestone hence may not capture or make suggestions in relation to the 4th milestone. Whilst reviewing the 5th milestone it is assumed that the 4th milestone has been reviewed and approved 🙂.
#### This P/R will be marked invalid since it has already been approved.

**Comment by jaspreet-singh-sahota** [comment]
> > # My question for the TSE,
> > My 5th milestone got approved and I have to make some changes in the 4th one which I have already completed in the 5th milestone. So, do I need to go back to the 4th milestone and repeat the same code again? or am I good to go?.
> > ## Note:- This is my 5th milestone pull request which I am sending for review instead of 4th.
> > Looking forward to your answer,
> > Best regards,
> > Jaspreet Singh
> 
> First of all, it is not a good practice to work on different milestones simultaneously. You have to work according to the order milestone as each milestone has its own specific learning objective. Now you need to work on the review of the 4th milestone. The person who reviewed the 5th milestone only focused on the requirements of the 5th milestone in the review of that particular milestone hence may not capture or make suggestions in relation to the 4th milestone. Whilst reviewing the 5th milestone it is assumed that the 4th milestone has been reviewed and approved slightly_smiling_face.
> #### This P/R will be marked invalid since it has already been approved.

Thank you for the reply @Forison,


I know it not a good practice to work on a different milestone at the same time. I totally agree with you on that, but it was mentioned in the microverse requirements that we should keep working on the next milestone while one milestone is under the review. 

Screenshot from 2020-09-17 05-22-34

I got your point of reviewing each milestone separately cause each milestone has specific requirements. And I really appreciate your time to reply to this. Thank you 😊
 
best regards, 
Jaspreet

**Pull request merged**
